---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webproject
  labels:
    app: webproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webproject
  template:
    metadata:
      labels:
        app: webproject
    spec:
      containers:
      - name: webproject
        image: chndra/webproject:692
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webproject
  labels:
    app: webproject
spec:
  type: LoadBalancer
  ports:  
    - port: 80
      targetPort: 8080
  selector:
    app: webproject
